import type { AmenityKey, Furnishing, PropertyType } from "../../src/config/property-options";
import type { SeedAgentSlug } from "./agents";
import {
  apartmentExteriors as apt,
  bathrooms as bath,
  bedrooms as bed,
  kitchens as kit,
  legacyImages,
  livingRooms as liv,
  placeImages,
  terraces,
  villaExteriors as villa,
  type SeedImage,
} from "./images";

const CRORE = 10_000_000;
const LAKH = 100_000;

export interface SeedProperty {
  title: string;
  headline: string;
  description: string;
  listingType: "sale" | "rent";
  propertyType: PropertyType;
  availability?: "available" | "under_offer" | "sold" | "rented";
  price: number;
  previousPrice?: number;
  onRequest?: boolean;
  bedrooms: number;
  bathrooms: number;
  areaSqft: number;
  landAreaSqft?: number;
  parking: number;
  yearBuilt?: number;
  floors?: number;
  floorLevel?: number;
  furnishing?: Furnishing;
  amenities: AmenityKey[];
  featured?: boolean;
  exclusive?: boolean;
  newConstruction?: boolean;
  city: string;
  neighbourhood: string;
  displayAddress: string;
  coordinates: [lat: number, lng: number];
  showExactLocation?: boolean;
  images: SeedImage[];
  agent: SeedAgentSlug;
  daysAgo: number;
  virtualTourUrl?: string;
}

const pick = (list: SeedImage[], ...indexes: number[]) =>
  indexes.map((i) => list[i % list.length]!);

export const seedProperties: SeedProperty[] = [
  {
    title: "Gulshan Lakefront Penthouse",
    headline: "A full-floor penthouse with a private roof terrace above Gulshan Lake.",
    description: `Occupying the top two floors of a boutique lakeside building, this penthouse is arranged around a double-height living room that opens onto a wraparound terrace facing the water.

The principal suite takes the quieter side of the plan, with a dressing room and a bathroom finished in honed stone. Three further bedrooms each have their own bathroom, and a separate family room on the upper level opens to the roof terrace and its plunge pool.

The building has a private lift lobby on each floor, full-load generator backup, round-the-clock security and parking for four cars.`,
    listingType: "sale",
    propertyType: "penthouse",
    price: 24.5 * CRORE,
    bedrooms: 5,
    bathrooms: 6,
    areaSqft: 6200,
    parking: 4,
    yearBuilt: 2022,
    floors: 2,
    floorLevel: 9,
    furnishing: "semi_furnished",
    amenities: [
      "terrace",
      "rooftop",
      "pool",
      "lake_view",
      "city_view",
      "smart_home",
      "central_ac",
      "lift",
      "concierge",
      "security_24h",
      "generator",
      "chef_kitchen",
      "walk_in_closet",
    ],
    featured: true,
    exclusive: true,
    city: "dhaka",
    neighbourhood: "gulshan",
    displayAddress: "Lakeside, Gulshan 2",
    coordinates: [23.7964, 90.4161],
    images: [
      ...pick(liv, 3),
      terraces[1]!,
      ...pick(liv, 14),
      ...pick(kit, 5),
      ...pick(bed, 0, 3),
      ...pick(bath, 1),
      terraces[0]!,
    ],
    agent: "ayesha-rahman",
    daysAgo: 4,
  },
  {
    title: "Banani Garden Duplex",
    headline: "A ground-and-first-floor duplex with its own landscaped garden.",
    description: `Rare in Banani, this duplex has a private walled garden that wraps around the living and dining rooms on the ground floor.

Upstairs, four bedrooms are arranged around a central family room, and the principal bedroom opens onto a covered terrace overlooking the garden. A study, staff quarters and a utility room complete the plan.`,
    listingType: "sale",
    propertyType: "duplex",
    price: 13.8 * CRORE,
    previousPrice: 14.5 * CRORE,
    bedrooms: 4,
    bathrooms: 5,
    areaSqft: 4800,
    parking: 3,
    yearBuilt: 2018,
    floors: 2,
    furnishing: "unfurnished",
    amenities: [
      "garden",
      "terrace",
      "park_view",
      "central_ac",
      "study",
      "staff_quarters",
      "security_24h",
      "generator",
    ],
    city: "dhaka",
    neighbourhood: "banani",
    displayAddress: "Road 11, Banani",
    coordinates: [23.7946, 90.4031],
    images: [villa[13]!, ...pick(liv, 5, 7), ...pick(kit, 2), ...pick(bed, 4), ...pick(bath, 2)],
    agent: "farhan-chowdhury",
    daysAgo: 12,
  },
  {
    title: "Baridhara Diplomatic Zone Residence",
    headline: "A calm four-bedroom apartment on one of Baridhara's quietest roads.",
    description: `This apartment occupies a whole floor of a low-rise building in the diplomatic zone, with windows on all four sides.

Reception rooms flow from a generous entrance hall, and a separate dining room seats ten. Each of the four bedrooms has its own bathroom, and the principal suite includes a walk-in wardrobe.`,
    listingType: "sale",
    propertyType: "apartment",
    price: 11.2 * CRORE,
    bedrooms: 4,
    bathrooms: 4,
    areaSqft: 4200,
    parking: 2,
    yearBuilt: 2016,
    floorLevel: 3,
    furnishing: "unfurnished",
    amenities: [
      "balcony",
      "park_view",
      "central_ac",
      "lift",
      "security_24h",
      "gated_community",
      "generator",
      "walk_in_closet",
    ],
    exclusive: true,
    city: "dhaka",
    neighbourhood: "baridhara",
    displayAddress: "Diplomatic Zone, Baridhara",
    coordinates: [23.8019, 90.4234],
    images: [apt[3]!, ...pick(liv, 10, 12), ...pick(kit, 6), ...pick(bed, 6), ...pick(bath, 0)],
    agent: "ayesha-rahman",
    daysAgo: 20,
  },
  {
    title: "Dhanmondi Lakeside Apartment",
    headline: "Light-filled three-bedroom apartment a short walk from Dhanmondi Lake.",
    description: `Set on a tree-lined road close to the lake, this apartment has a bright, dual-aspect living room and a balcony facing the trees.

The kitchen has been refitted with stone worktops, and all three bedrooms are doubles with fitted storage.`,
    listingType: "sale",
    propertyType: "apartment",
    price: 6.9 * CRORE,
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 3100,
    parking: 1,
    yearBuilt: 2014,
    floorLevel: 5,
    furnishing: "unfurnished",
    amenities: ["balcony", "lake_view", "lift", "security_24h", "generator"],
    city: "dhaka",
    neighbourhood: "dhanmondi",
    displayAddress: "Near Dhanmondi Lake",
    coordinates: [23.7468, 90.3755],
    images: [apt[7]!, ...pick(liv, 15), ...pick(kit, 4), ...pick(bed, 7), ...pick(bath, 4)],
    agent: "imran-hossain",
    daysAgo: 33,
  },
  {
    title: "Bashundhara Contemporary Villa",
    headline: "A newly completed villa with pool, garden and six bedroom suites.",
    description: `Completed this year, this detached villa sits on a corner plot with a landscaped garden and a lap pool along its southern edge.

The ground floor is almost entirely glazed towards the garden, with a living room, dining room and kitchen arranged as one long space. Six bedroom suites occupy the upper floors, and the lower ground floor houses a gym, cinema room and staff accommodation.`,
    listingType: "sale",
    propertyType: "villa",
    price: 32 * CRORE,
    bedrooms: 6,
    bathrooms: 7,
    areaSqft: 7500,
    landAreaSqft: 7200,
    parking: 4,
    yearBuilt: 2026,
    floors: 3,
    furnishing: "unfurnished",
    amenities: [
      "pool",
      "garden",
      "terrace",
      "gym",
      "home_cinema",
      "smart_home",
      "central_ac",
      "chef_kitchen",
      "staff_quarters",
      "security_24h",
      "generator",
      "ev_charging",
      "solar_power",
    ],
    featured: true,
    newConstruction: true,
    city: "dhaka",
    neighbourhood: "bashundhara",
    displayAddress: "Block D, Bashundhara R/A",
    coordinates: [23.8207, 90.4512],
    images: [
      legacyImages.gardenVilla,
      villa[3]!,
      villa[6]!,
      ...pick(liv, 6, 0),
      ...pick(kit, 3),
      ...pick(bed, 1),
      ...pick(bath, 3),
    ],
    agent: "farhan-chowdhury",
    daysAgo: 2,
    virtualTourUrl: "",
  },
  {
    title: "Gulshan 2 Signature Apartment",
    headline: "A new four-bedroom apartment with a deep terrace off the living room.",
    description: `Part of a newly completed building of just eight apartments, this home is laid out around a long living and dining room that opens onto a covered terrace.

Specifications include engineered timber floors, a fully fitted kitchen with integrated appliances, and smart-home lighting and climate control throughout.`,
    listingType: "sale",
    propertyType: "apartment",
    price: 9.6 * CRORE,
    bedrooms: 4,
    bathrooms: 4,
    areaSqft: 3800,
    parking: 2,
    yearBuilt: 2026,
    floorLevel: 6,
    furnishing: "unfurnished",
    amenities: [
      "terrace",
      "city_view",
      "smart_home",
      "central_ac",
      "lift",
      "security_24h",
      "generator",
      "gym",
    ],
    newConstruction: true,
    city: "dhaka",
    neighbourhood: "gulshan",
    displayAddress: "Gulshan 2",
    coordinates: [23.7949, 90.4128],
    images: [apt[1]!, ...pick(liv, 1, 13), ...pick(kit, 1), ...pick(bed, 5), ...pick(bath, 5)],
    agent: "ayesha-rahman",
    daysAgo: 7,
  },
  {
    title: "Furnished Gulshan Family Apartment",
    headline: "A fully furnished four-bedroom apartment, ready to move into.",
    description: `Furnished throughout with a calm, neutral scheme, this apartment is set up for a family or a relocating executive.

The living room opens to a long balcony, and the kitchen is fully equipped. Utilities, generator maintenance and building security are managed by the building's committee.`,
    listingType: "rent",
    propertyType: "apartment",
    price: 4.5 * LAKH,
    bedrooms: 4,
    bathrooms: 4,
    areaSqft: 3400,
    parking: 2,
    yearBuilt: 2019,
    floorLevel: 4,
    furnishing: "furnished",
    amenities: ["balcony", "lake_view", "central_ac", "lift", "security_24h", "generator"],
    city: "dhaka",
    neighbourhood: "gulshan",
    displayAddress: "Gulshan 1",
    coordinates: [23.7808, 90.4167],
    images: [...pick(liv, 8, 9), ...pick(kit, 0), ...pick(bed, 2), ...pick(bath, 0), apt[5]!],
    agent: "ayesha-rahman",
    daysAgo: 3,
  },
  {
    title: "Banani Executive Suite",
    headline: "A compact, fully serviced three-bedroom apartment close to Banani's restaurants.",
    description: `Ideal for a professional couple or a small family, this apartment is furnished to a high standard and includes weekly housekeeping.

The open-plan living space faces south over the street's trees, and the building has a small residents' gym.`,
    listingType: "rent",
    propertyType: "apartment",
    price: 2.8 * LAKH,
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 2200,
    parking: 1,
    yearBuilt: 2021,
    floorLevel: 7,
    furnishing: "furnished",
    amenities: ["balcony", "city_view", "gym", "lift", "security_24h", "generator", "central_ac"],
    city: "dhaka",
    neighbourhood: "banani",
    displayAddress: "Banani",
    coordinates: [23.7911, 90.4035],
    images: [...pick(liv, 16), ...pick(kit, 4), ...pick(bed, 6), ...pick(bath, 6), apt[6]!],
    agent: "farhan-chowdhury",
    daysAgo: 9,
  },
  {
    title: "Baridhara Embassy-Row Townhouse",
    headline: "A five-bedroom townhouse with a private garden in the diplomatic zone.",
    description: `Arranged over three floors, this townhouse combines formal reception rooms for entertaining with a private family floor above.

A walled garden runs the width of the house, and the property has its own gated parking for three cars. The landlord will consider requests for furnishing.`,
    listingType: "rent",
    propertyType: "townhouse",
    price: 8.5 * LAKH,
    bedrooms: 5,
    bathrooms: 6,
    areaSqft: 5200,
    landAreaSqft: 3600,
    parking: 3,
    yearBuilt: 2012,
    floors: 3,
    furnishing: "semi_furnished",
    amenities: [
      "garden",
      "terrace",
      "security_24h",
      "gated_community",
      "generator",
      "staff_quarters",
      "study",
    ],
    featured: true,
    city: "dhaka",
    neighbourhood: "baridhara",
    displayAddress: "Diplomatic Zone, Baridhara",
    coordinates: [23.7995, 90.4251],
    images: [villa[0]!, ...pick(liv, 4, 11), ...pick(kit, 6), ...pick(bed, 3), ...pick(bath, 2)],
    agent: "ayesha-rahman",
    daysAgo: 15,
  },
  {
    title: "Dhanmondi Heritage House",
    headline: "A restored family house with a mature garden on a quiet road.",
    description: `Built in the late 1980s and carefully restored, this house retains its original terrazzo floors and generous ceiling heights.

Five bedrooms are spread across two floors, and the garden is shaded by established trees.`,
    listingType: "rent",
    propertyType: "house",
    price: 3.9 * LAKH,
    bedrooms: 5,
    bathrooms: 4,
    areaSqft: 4600,
    landAreaSqft: 5400,
    parking: 2,
    yearBuilt: 1988,
    floors: 2,
    furnishing: "unfurnished",
    amenities: ["garden", "terrace", "study", "staff_quarters", "generator"],
    city: "dhaka",
    neighbourhood: "dhanmondi",
    displayAddress: "Dhanmondi",
    coordinates: [23.7432, 90.3721],
    images: [villa[13]!, ...pick(liv, 7), ...pick(kit, 2), ...pick(bed, 7), ...pick(bath, 4)],
    agent: "imran-hossain",
    daysAgo: 26,
  },
  {
    title: "Gulshan Sky Penthouse for Lease",
    headline: "A penthouse with a rooftop pool and uninterrupted city views.",
    description: `Available on a long lease, this penthouse occupies the top floor of one of Gulshan's taller residential buildings, with a private rooftop pool and lounge.

Interiors are fully furnished, and the lease can include the services of the building concierge.`,
    listingType: "rent",
    propertyType: "penthouse",
    price: 9.5 * LAKH,
    bedrooms: 4,
    bathrooms: 5,
    areaSqft: 5400,
    parking: 3,
    yearBuilt: 2023,
    floorLevel: 14,
    furnishing: "furnished",
    amenities: [
      "pool",
      "rooftop",
      "terrace",
      "city_view",
      "smart_home",
      "concierge",
      "lift",
      "security_24h",
      "generator",
      "central_ac",
    ],
    featured: true,
    exclusive: true,
    city: "dhaka",
    neighbourhood: "gulshan",
    displayAddress: "Gulshan 2",
    coordinates: [23.7972, 90.4139],
    images: [
      ...pick(liv, 13),
      terraces[1]!,
      ...pick(liv, 17),
      ...pick(kit, 5),
      ...pick(bed, 0),
      ...pick(bath, 1),
    ],
    agent: "ayesha-rahman",
    daysAgo: 1,
  },
  {
    title: "Khulshi Hillside Residence",
    headline: "A detached house with terraced gardens and views over Chattogram.",
    description: `Set into the hillside, this house steps down across three levels, each with its own terrace and garden.

The main living spaces face west towards the city and the hills beyond. Five bedrooms, a study and a separate guest suite make it well suited to a large family.`,
    listingType: "sale",
    propertyType: "house",
    price: 12.5 * CRORE,
    bedrooms: 5,
    bathrooms: 5,
    areaSqft: 5800,
    landAreaSqft: 9000,
    parking: 3,
    yearBuilt: 2015,
    floors: 3,
    furnishing: "unfurnished",
    amenities: [
      "garden",
      "terrace",
      "city_view",
      "study",
      "security_24h",
      "generator",
      "staff_quarters",
    ],
    featured: true,
    city: "chattogram",
    neighbourhood: "khulshi",
    displayAddress: "Khulshi Hill",
    coordinates: [22.3624, 91.8067],
    images: [villa[9]!, ...pick(liv, 2, 10), ...pick(kit, 0), ...pick(bed, 4), ...pick(bath, 5)],
    agent: "nadia-karim",
    daysAgo: 18,
  },
  {
    title: "Nasirabad Hilltop Apartment",
    headline: "A three-bedroom apartment with long views, close to the city's clubs.",
    description: `On the upper floor of a well-kept building, this apartment has a generous living room with a balcony along its full width.

The building is managed by an active owners' association and has a generator and lift.`,
    listingType: "sale",
    propertyType: "apartment",
    price: 4.2 * CRORE,
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 2950,
    parking: 1,
    yearBuilt: 2017,
    floorLevel: 8,
    furnishing: "unfurnished",
    amenities: ["balcony", "city_view", "lift", "security_24h", "generator"],
    city: "chattogram",
    neighbourhood: "nasirabad",
    displayAddress: "Nasirabad Housing Society",
    coordinates: [22.3671, 91.8172],
    images: [apt[2]!, ...pick(liv, 12), ...pick(kit, 1), ...pick(bed, 2), ...pick(bath, 0)],
    agent: "nadia-karim",
    daysAgo: 40,
  },
  {
    title: "Khulshi Family Apartment to Let",
    headline: "A spacious three-bedroom apartment in leafy Khulshi.",
    description: `A well-proportioned apartment on a quiet residential road in Khulshi, with a large living room and a balcony facing the hills.`,
    listingType: "rent",
    propertyType: "apartment",
    price: 1.6 * LAKH,
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 2600,
    parking: 1,
    yearBuilt: 2015,
    floorLevel: 2,
    furnishing: "semi_furnished",
    amenities: ["balcony", "park_view", "lift", "security_24h", "generator"],
    city: "chattogram",
    neighbourhood: "khulshi",
    displayAddress: "Khulshi",
    coordinates: [22.3596, 91.8112],
    images: [...pick(liv, 11), ...pick(kit, 6), ...pick(bed, 5), ...pick(bath, 2), apt[0]!],
    agent: "nadia-karim",
    daysAgo: 11,
  },
  {
    title: "Inani Beachfront Villa",
    headline: "A villa with its own pool, facing the Bay of Bengal across a quiet beach.",
    description: `Positioned between the Marine Drive and the sea, this villa looks directly over a quiet stretch of beach near Inani.

A long infinity pool runs along the seaward terrace, and the main living spaces open fully to it. Five bedroom suites are arranged in two wings, giving guests privacy from the main house.`,
    listingType: "sale",
    propertyType: "villa",
    price: 18.5 * CRORE,
    bedrooms: 5,
    bathrooms: 6,
    areaSqft: 6800,
    landAreaSqft: 14000,
    parking: 4,
    yearBuilt: 2024,
    floors: 2,
    furnishing: "furnished",
    amenities: [
      "pool",
      "waterfront",
      "sea_view",
      "terrace",
      "garden",
      "outdoor_kitchen",
      "central_ac",
      "security_24h",
      "generator",
      "solar_power",
    ],
    featured: true,
    exclusive: true,
    city: "coxs-bazar",
    neighbourhood: "inani",
    displayAddress: "Marine Drive, Inani",
    coordinates: [21.2381, 92.0432],
    images: [
      legacyImages.coastalVilla,
      villa[11]!,
      villa[7]!,
      ...pick(liv, 17),
      ...pick(bed, 1),
      ...pick(bath, 1),
      placeImages.coxsBazar[2]!,
    ],
    agent: "nadia-karim",
    daysAgo: 6,
  },
  {
    title: "Marine Drive Ocean-View Apartment",
    headline: "A new three-bedroom apartment with sea views from every room.",
    description: `Part of a small new development on the Marine Drive, this apartment faces the sea with a deep balcony running the width of the living room.

The development includes a shared pool and landscaped grounds, and a management service is available for owners who rent out their homes.`,
    listingType: "sale",
    propertyType: "apartment",
    price: 3.4 * CRORE,
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1850,
    parking: 1,
    yearBuilt: 2026,
    floorLevel: 4,
    furnishing: "furnished",
    amenities: ["sea_view", "balcony", "pool", "lift", "security_24h", "generator"],
    newConstruction: true,
    city: "coxs-bazar",
    neighbourhood: "inani",
    displayAddress: "Marine Drive",
    coordinates: [21.2565, 92.0369],
    images: [
      ...pick(liv, 17),
      placeImages.coxsBazar[1]!,
      ...pick(kit, 4),
      ...pick(bed, 6),
      ...pick(bath, 6),
    ],
    agent: "nadia-karim",
    daysAgo: 10,
  },
  {
    title: "Kolatoli Sea-View Penthouse",
    headline: "A top-floor penthouse moments from the beach. Price on request.",
    description: `This penthouse occupies the top floor of a residential building in Kolatoli, with a roof terrace looking out across the bay.

Details are shared with qualified buyers following an introductory conversation with our advisor.`,
    listingType: "sale",
    propertyType: "penthouse",
    price: 7.8 * CRORE,
    onRequest: true,
    bedrooms: 4,
    bathrooms: 4,
    areaSqft: 3600,
    parking: 2,
    yearBuilt: 2020,
    floorLevel: 10,
    furnishing: "semi_furnished",
    amenities: ["sea_view", "rooftop", "terrace", "lift", "security_24h", "generator"],
    exclusive: true,
    city: "coxs-bazar",
    neighbourhood: "kolatoli",
    displayAddress: "Kolatoli",
    coordinates: [21.4114, 92.0087],
    images: [
      terraces[0]!,
      ...pick(liv, 3),
      ...pick(bed, 3),
      ...pick(bath, 3),
      placeImages.coxsBazar[0]!,
    ],
    agent: "nadia-karim",
    daysAgo: 22,
  },
  {
    title: "Kolatoli Holiday Apartment",
    headline: "A furnished two-bedroom apartment a short walk from the beach.",
    description: `A practical, fully furnished apartment for long stays by the sea, close to Kolatoli's restaurants and the main beach.`,
    listingType: "rent",
    propertyType: "apartment",
    price: 1.1 * LAKH,
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1400,
    parking: 1,
    yearBuilt: 2019,
    floorLevel: 5,
    furnishing: "furnished",
    amenities: ["sea_view", "balcony", "lift", "security_24h", "generator"],
    city: "coxs-bazar",
    neighbourhood: "kolatoli",
    displayAddress: "Kolatoli",
    coordinates: [21.4136, 92.0111],
    images: [...pick(liv, 18), ...pick(bed, 5), ...pick(kit, 2), placeImages.coxsBazar[3]!],
    agent: "nadia-karim",
    daysAgo: 30,
  },
  {
    title: "Sylhet Tea Country Retreat",
    headline: "A garden villa surrounded by tea estates, two hours' drive from the city.",
    description: `Set in mature gardens on the edge of the tea country, this villa was designed as a family retreat, with deep verandas and a living room that opens to the lawn.

Four bedrooms, a separate guest cottage and staff quarters make it suitable for extended family visits throughout the year.`,
    listingType: "sale",
    propertyType: "villa",
    price: 8.9 * CRORE,
    bedrooms: 4,
    bathrooms: 5,
    areaSqft: 5200,
    landAreaSqft: 21000,
    parking: 4,
    yearBuilt: 2019,
    floors: 2,
    furnishing: "semi_furnished",
    amenities: [
      "garden",
      "terrace",
      "park_view",
      "staff_quarters",
      "generator",
      "solar_power",
      "fireplace",
    ],
    featured: true,
    city: "sylhet",
    neighbourhood: "",
    displayAddress: "Outskirts of Sylhet",
    coordinates: [24.9312, 91.9076],
    images: [
      placeImages.sylhet[0]!,
      villa[1]!,
      ...pick(liv, 4),
      ...pick(bed, 4),
      ...pick(kit, 3),
      placeImages.sylhet[2]!,
    ],
    agent: "imran-hossain",
    daysAgo: 14,
  },
  {
    title: "Sylhet Garden Bungalow",
    headline: "A single-storey bungalow with a large lawn, available for long lets.",
    description: `A comfortable single-storey home with three bedrooms, a broad veranda and a large lawn, in a quiet residential area of Sylhet.`,
    listingType: "rent",
    propertyType: "house",
    price: 1.4 * LAKH,
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 3200,
    landAreaSqft: 8000,
    parking: 2,
    yearBuilt: 2010,
    floors: 1,
    furnishing: "unfurnished",
    amenities: ["garden", "terrace", "generator"],
    city: "sylhet",
    neighbourhood: "",
    displayAddress: "Sylhet",
    coordinates: [24.9006, 91.8702],
    images: [villa[13]!, ...pick(liv, 10), ...pick(bed, 7), placeImages.sylhet[1]!],
    agent: "imran-hossain",
    daysAgo: 45,
  },
  {
    title: "Gulshan Avenue Corner Apartment",
    headline: "A corner apartment with windows on two sides, minutes from Gulshan Avenue.",
    description: `Bright and well laid out, this three-bedroom apartment occupies a corner of a well-maintained building just off Gulshan Avenue.`,
    listingType: "sale",
    propertyType: "apartment",
    availability: "under_offer",
    price: 7.2 * CRORE,
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 2750,
    parking: 2,
    yearBuilt: 2015,
    floorLevel: 5,
    furnishing: "unfurnished",
    amenities: ["balcony", "city_view", "lift", "security_24h", "generator"],
    city: "dhaka",
    neighbourhood: "gulshan",
    displayAddress: "Off Gulshan Avenue",
    coordinates: [23.7853, 90.4152],
    images: [
      apt[4]!,
      ...pick(liv, 2),
      legacyImages.brightInterior,
      ...pick(bed, 2),
      ...pick(bath, 5),
    ],
    agent: "ayesha-rahman",
    daysAgo: 52,
  },
  {
    title: "Banani Lakeview Penthouse",
    headline: "A five-bedroom penthouse overlooking Banani Lake.",
    description: `A generous penthouse with a wide terrace facing the lake. This home has now been sold; similar homes in Banani are available through our advisors.`,
    listingType: "sale",
    propertyType: "penthouse",
    availability: "sold",
    price: 16.8 * CRORE,
    bedrooms: 5,
    bathrooms: 5,
    areaSqft: 5100,
    parking: 3,
    yearBuilt: 2021,
    floorLevel: 11,
    furnishing: "semi_furnished",
    amenities: [
      "terrace",
      "lake_view",
      "rooftop",
      "lift",
      "security_24h",
      "generator",
      "central_ac",
    ],
    city: "dhaka",
    neighbourhood: "banani",
    displayAddress: "Banani Lake",
    coordinates: [23.7962, 90.4066],
    images: [...pick(liv, 0), terraces[0]!, ...pick(kit, 5), ...pick(bed, 1)],
    agent: "farhan-chowdhury",
    daysAgo: 60,
  },
  {
    title: "Bashundhara Garden Townhouse",
    headline: "A four-bedroom townhouse with a garden in a newer part of Bashundhara.",
    description: `Finished to a contemporary specification, this townhouse has an open-plan ground floor that opens to a private garden, with four bedrooms above.`,
    listingType: "sale",
    propertyType: "townhouse",
    price: 7.9 * CRORE,
    bedrooms: 4,
    bathrooms: 4,
    areaSqft: 4100,
    landAreaSqft: 3000,
    parking: 2,
    yearBuilt: 2025,
    floors: 3,
    furnishing: "unfurnished",
    amenities: [
      "garden",
      "terrace",
      "smart_home",
      "central_ac",
      "security_24h",
      "gated_community",
      "generator",
    ],
    newConstruction: true,
    city: "dhaka",
    neighbourhood: "bashundhara",
    displayAddress: "Bashundhara R/A",
    coordinates: [23.8168, 90.4469],
    images: [villa[2]!, ...pick(liv, 6), ...pick(kit, 3), ...pick(bed, 5), ...pick(bath, 4)],
    agent: "farhan-chowdhury",
    daysAgo: 8,
  },
];
